# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab6de05faa77d267540318127df75d8698a0b4a0d2ffc57c5a34251f3172b78b08c13608a1806967ba89095b0e0e9ffcce763305f3765d57f328a9a132fb1d0

test:
  secret_key_base: 7b95a9c1d491d9ec25b6fe69b049dceb95d9d138d58f7686e02f62f78c7c6dde0e908906945305e0458646aaeb4ba032491adce186f5eac831306e1da3b12b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
